### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by scargill** [mharizanov/ESP8266_Relay_Board#1]
This is stunningly similar to the work we've just about completed over the weekend! Except we're using node-red to provide time etc on the other hand you've done what looks like a cracking job on the scheduler.
Any change of making this so it will compile with Eclipse on Windows? OR provide a set of binaries so I can give this a go?

**Comment by mharizanov** [comment]
Hi Peter,
I think we will need a community effort in order to make this compile under Windows, I'm pretty sure the folks at esp8266.com will crack that one in no time. In the mean time try these binaries https://dl.dropboxusercontent.com/u/18771283/wifirelay.zip

0x00000.bin goes to 0x00000
0x40000.bin goes to 0x40000
webpages.espfs goes to 0x12000

**Comment by scargill** [comment]
Nope- bad page it says….error 404 no page…. Something up with the link.  Another?   (I am used to using Dropbox so it’s not me.) :)

**Comment by mharizanov** [comment]
Give it another try, was still syncing

**Comment by bobricius** [comment]
Hi, I tested firmware from zip file, working great, Is this bin  firmware contain oled support? where is connected sda, scl? display address? Thermostat working only with relay1? this absolute best project on esp8266.
Maybe you can display on oled, ip address, desired temperature, wifi status, signal strengh ... selectable from web ui, this oled display have great resolution and with small font it can display much more. Great job!

**Comment by mharizanov** [comment]
Bob,
lets keep the topic of the issue to compiling under Windows
Cheers

**Comment by mharizanov** [comment]
CHERTS has added the project to his examples

http://www.esp8266.com/viewtopic.php?f=9&t=820&p=4639#p4639

Changelog:
v2.0.0 (26.03.2015):
+ Added new examples:
...
ESP8266_Relay_Board - "Three Channel WiFi Relay/Thermostat Board", (compiled, works correctly), the original source https://github.com/mharizanov/ESP8266_Relay_Board
+ Added new utility:

**Comment by scargill** [comment]
I've written by email but it's probably worth noting here, I got Chert's updates and sure enough your code is there - and it compiles - but there are rather more flash options than I'm use to... I assume CLEAN and ALL compiles the lot. Which flash options are needed to completely flash the chip?

**Comment by phyrexia** [comment]
I just wantest to test the features ins a protoboard, but code wont compile in osx is a nigthmare, and in the esp official VM wont compile either, demo file should be provided, even as a reference.

**Comment by zkopf** [comment]
Thanks for sharing the code with us, the link for binaries is broken, if you won't mind making it available again.

**Comment by svitky** [comment]
Hallo to everyone
I am completely lost...:-(
I cannot compile the files from the github source.. everytime I get an error... no big deal for me.. I have only one water boiler which I am trying to make smarter... If it is possible for someone to send me 0x0000.bin, 0x40000.bin and webpages... file to an email. I woud be lucky as a pig in a swam... I am trying to make it work for 2 weeks and I am about to give up...
the link https://dl.dropboxusercontent.com/u/18771283/wifirelay.zip is not working.
nice day
thanks
