### ISSUE TITLE
TLS and certificate

### ISSUE THREAD

**Issue by stefanoco** [mharizanov/ESP8266_Relay_Board#14]
While waiting for my first ESP8266 Wifi Relay to be delivered by OpenEnergyMonitor, I'm not able to understand from the documentation how it would be possible to upload a ca.crt (certificate) for MQTT TLS Authentication. Any hint?

**Comment by mharizanov** [comment]
Hello,
Certificate verification won't be possible with this firmware; The TLS checkbox only enables connections to MQTT broker over TLS, but doesn't perform certificate validation; One of the things to consider is the availability of NTP, which is needed to verify certificate expiration. You will be surprised how many ISPs block NTP.
You are free to extend the firmware to support certificate verification

**Comment by stefanoco** [comment]
ok thanks a lot, I will consider extending the firmware when I have time.
