### ISSUE TITLE
KRACK Vulnerability

### ISSUE THREAD

**Issue by kylix34** [mharizanov/ESP8266_Relay_Board#15]
Hello Martin,

any hint about what has to be changed in order to patch the KRACK vulnerability?

Thanks!

**Comment by mharizanov** [comment]
Hi,
it is just a matter of switching to the latest https://github.com/espressif/ESP8266_NONOS_SDK , the libraries were patched there.
Could be quite a challenge since this branch hasn't been maintained for a while and the switch to version SDK 2.1 may not be trivial. If you get it going, please make a pull request

**Comment by kylix34** [comment]
Hi Martin!
Until now I used these steps for building the toolchain: https://github.com/esp8266/esp8266-wiki/wiki/toolchain

I see it uses a very old sdk version: 0.9.3

Could you instruct on how to use the new 2.1.0 sdk version for building the toolchain?

Thanks!

**Comment by mharizanov** [comment]
Hi,
I'd rather use this setup: https://github.com/pfalcon/esp-open-sdk

**Comment by kylix34** [comment]
Hi Martin,

I managed to compile the toolchain using the new SDK but now, when trying to compile the thermostat code I get a lot of errors:
`felix@felix-VirtualBox:~/Desktop/ESP8266_Relay_Board-master/1ch_relay$ make
CC driver/i2c_oled.c
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:17:6: error: conflicting types for 'ets_isr_attach'
 void ets_isr_attach(int intr, void *handler, void *arg);
      ^
In file included from include/espmissingincludes.h:4:0,
                 from driver/i2c_oled.c:12:
/opt/Espressif/ESP8266_SDK/include/ets_sys.h:67:6: note: previous declaration of 'ets_isr_attach' was here
 void ets_isr_attach(int i, ets_isr_t func, void *arg);
      ^
In file included from include/driver/i2c.h:25:0,
                 from driver/i2c_oled.c:13:
/opt/Espressif/ESP8266_SDK/include/osapi.h:33:6: error: conflicting types for 'ets_delay_us'
 void ets_delay_us(uint16_t us);
      ^
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:49:6: note: previous declaration of 'ets_delay_us' was here
 void ets_delay_us(long us);
      ^
In file included from include/driver/i2c.h:25:0,
                 from driver/i2c_oled.c:13:
/opt/Espressif/ESP8266_SDK/include/osapi.h:34:6: error: conflicting types for 'ets_install_putc1'
 void ets_install_putc1(void (*p)(char c));
      ^
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:16:6: note: previous declaration of 'ets_install_putc1' was here
 void ets_install_putc1(void *routine);
      ^
In file included from include/driver/i2c.h:25:0,
                 from driver/i2c_oled.c:13:
/opt/Espressif/ESP8266_SDK/include/osapi.h:47:5: error: conflicting types for 'ets_strlen'
 int ets_strlen(const char *s);
     ^
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:27:8: note: previous declaration of 'ets_strlen' was here
 size_t ets_strlen(const char *s);
        ^
In file included from include/driver/i2c.h:25:0,
                 from driver/i2c_oled.c:13:
/opt/Espressif/ESP8266_SDK/include/osapi.h:48:5: error: conflicting types for 'ets_strncmp'
 int ets_strncmp(const char *s1, const char *s2, unsigned int n);
     ^
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:28:5: note: previous declaration of 'ets_strncmp' was here
 int ets_strncmp(const char *s1, const char *s2, int len);
     ^
In file included from include/driver/i2c.h:25:0,
                 from driver/i2c_oled.c:13:
/opt/Espressif/ESP8266_SDK/include/osapi.h:65:6: error: conflicting types for 'ets_timer_arm_new'
 void ets_timer_arm_new(os_timer_t *ptimer, uint32_t time, bool repeat_flag, bool ms_flag);
      ^
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:31:6: note: previous declaration of 'ets_timer_arm_new' was here
 void ets_timer_arm_new(ETSTimer *a, int b, int c, int isMstimer);
      ^
In file included from include/driver/i2c.h:25:0,
                 from driver/i2c_oled.c:13:
/opt/Espressif/ESP8266_SDK/include/osapi.h:90:15: error: conflicting types for 'os_random'
 unsigned long os_random(void);
               ^
In file included from driver/i2c_oled.c:12:0:
include/espmissingincludes.h:46:5: note: previous declaration of 'os_random' was here
 int os_random();
     ^
Makefile:197: recipe for target 'build/driver/i2c_oled.o' failed
make: *** [build/driver/i2c_oled.o] Error 1
felix@felix-VirtualBox:~/Desktop/ESP8266_Relay_Board-master/1ch_relay$ 
`
If you have any suggestion, please let me know.

Thanks!

**Comment by kylix34** [comment]
Removing the "DRIVER" folder (I don't use the i2c driver for the oled display) I get:

felix@felix-VirtualBox:~/Desktop/ESP8266_Relay_Board-master/1ch_relay$ make
CC user/mqtt.c
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:17:6: error: conflicting types for 'ets_isr_attach'
 void ets_isr_attach(int intr, void *handler, void *arg);
      ^
In file included from /opt/Espressif/ESP8266_SDK/include/os_type.h:28:0,
                 from include/user_interface.h:9,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/ets_sys.h:67:6: note: previous declaration of 'ets_isr_attach' was here
 void ets_isr_attach(int i, ets_isr_t func, void *arg);
      ^
In file included from include/arch/cc.h:40:0,
                 from include/lwip/arch.h:43,
                 from include/lwip/debug.h:35,
                 from include/lwip/opt.h:46,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/osapi.h:33:6: error: conflicting types for 'ets_delay_us'
 void ets_delay_us(uint16_t us);
      ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:49:6: note: previous declaration of 'ets_delay_us' was here
 void ets_delay_us(long us);
      ^
In file included from include/arch/cc.h:40:0,
                 from include/lwip/arch.h:43,
                 from include/lwip/debug.h:35,
                 from include/lwip/opt.h:46,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/osapi.h:34:6: error: conflicting types for 'ets_install_putc1'
 void ets_install_putc1(void (*p)(char c));
      ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:16:6: note: previous declaration of 'ets_install_putc1' was here
 void ets_install_putc1(void *routine);
      ^
In file included from include/arch/cc.h:40:0,
                 from include/lwip/arch.h:43,
                 from include/lwip/debug.h:35,
                 from include/lwip/opt.h:46,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/osapi.h:47:5: error: conflicting types for 'ets_strlen'
 int ets_strlen(const char *s);
     ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:27:8: note: previous declaration of 'ets_strlen' was here
 size_t ets_strlen(const char *s);
        ^
In file included from include/arch/cc.h:40:0,
                 from include/lwip/arch.h:43,
                 from include/lwip/debug.h:35,
                 from include/lwip/opt.h:46,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/osapi.h:48:5: error: conflicting types for 'ets_strncmp'
 int ets_strncmp(const char *s1, const char *s2, unsigned int n);
     ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:28:5: note: previous declaration of 'ets_strncmp' was here
 int ets_strncmp(const char *s1, const char *s2, int len);
     ^
In file included from include/arch/cc.h:40:0,
                 from include/lwip/arch.h:43,
                 from include/lwip/debug.h:35,
                 from include/lwip/opt.h:46,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/osapi.h:65:6: error: conflicting types for 'ets_timer_arm_new'
 void ets_timer_arm_new(os_timer_t *ptimer, uint32_t time, bool repeat_flag, bool ms_flag);
      ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:31:6: note: previous declaration of 'ets_timer_arm_new' was here
 void ets_timer_arm_new(ETSTimer *a, int b, int c, int isMstimer);
      ^
In file included from include/arch/cc.h:40:0,
                 from include/lwip/arch.h:43,
                 from include/lwip/debug.h:35,
                 from include/lwip/opt.h:46,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
/opt/Espressif/ESP8266_SDK/include/osapi.h:90:15: error: conflicting types for 'os_random'
 unsigned long os_random(void);
               ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:46:5: note: previous declaration of 'os_random' was here
 int os_random();
     ^
In file included from user/mqtt.c:36:0:
/opt/Espressif/ESP8266_SDK/include/mem.h:40:7: error: conflicting types for 'pvPortMalloc'
 void *pvPortMalloc (size_t sz, const char *, unsigned);
       ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:39:7: note: previous declaration of 'pvPortMalloc' was here
 void *pvPortMalloc(size_t xWantedSize);
       ^
In file included from user/mqtt.c:36:0:
/opt/Espressif/ESP8266_SDK/include/mem.h:41:6: error: conflicting types for 'vPortFree'
 void vPortFree (void *p, const char *, unsigned);
      ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:42:6: note: previous declaration of 'vPortFree' was here
 void vPortFree(void *ptr);
      ^
In file included from user/mqtt.c:36:0:
/opt/Espressif/ESP8266_SDK/include/mem.h:42:7: error: conflicting types for 'pvPortZalloc'
 void *pvPortZalloc (size_t sz, const char *, unsigned);
       ^
In file included from include/lwipopts.h:2034:0,
                 from include/lwip/opt.h:45,
                 from include/lwip/ip_addr.h:35,
                 from include/ip_addr.h:2,
                 from include/user_interface.h:13,
                 from user/mqtt.c:32:
include/espmissingincludes.h:40:7: note: previous declaration of 'pvPortZalloc' was here
 void *pvPortZalloc(size_t);
       ^
Makefile:197: recipe for target 'build/user/mqtt.o' failed
make: *** [build/user/mqtt.o] Error 1

**Comment by mharizanov** [comment]
Yes, this is typical when the function prototypes finally appeared in the SDK or the declarations changed.

for example ets_isr_attach was missing before and therefore declared in espmissingincludes.h, however with the latest SDK the parameter types changed as well so now you end up with two conflicting declarations of the same function:

> include/espmissingincludes.h
> void ets_isr_attach(int intr, void *handler, void *arg); 

vs 

> /opt/Espressif/ESP8266_SDK/include/ets_sys.h
> void ets_isr_attach(int i, ets_isr_t func, void *arg);

To resolve this you will need to adjust the .h files and most probably the C code that uses them so that the correct parameter types are used.

repeat that with every error in the error log and eventually you will be able to compile..

**Comment by kylix34** [comment]
Thanks Martin! I'm not a programmer but I'll give it a try. In case you have a few minutes I'd appreciate if you could give me just one example based on the Thermostat code and I'l go ahead.

**Comment by kylix34** [comment]
I finally managed to compile it all (SDK 2.1.0) by doing these changes:

1. Comment in espmissingincludes.h:

//void ets_install_putc1(void *routine);
//void ets_isr_attach(int intr, void *handler, void *arg);
//size_t ets_strlen(const char *s);
//int ets_strncmp(const char *s1, const char *s2, int len);
//void ets_timer_arm_new(ETSTimer *a, int b, int c, int isMstimer);
//void pvPortFree(void *ptr);
//void *pvPortMalloc(size_t xWantedSize);
//void *pvPortZalloc(size_t);
//void vPortFree(void *ptr);
//void *vPortMalloc(size_t xWantedSize);
//int os_random();
//void ets_delay_us(long us);

2. In pwm.c, at the end of the file:
  changed
    ETS_FRC_TIMER1_INTR_ATTACH(pwm_tim1_intr_handler, NULL);
  into
    ETS_FRC_TIMER1_INTR_ATTACH((ets_isr_t)pwm_tim1_intr_handler, NULL);

3. In io.h, added:
extern char currGPIO13State;
extern char currGPIO15State;

4. In osapi.h changed:
void ets_delay_us(uint16_t us);
	into:
void ets_delay_us(long us);

5. In ds18b20.c commented the following line:
	//PIN_PULLDWN_DIS(PERIPHS_IO_MUX_GPIO2_U);

6. In the Makefile, CFLAGS, I added: -Wno-implicit-function-declaration

I didn't test yet the compiled firmware.

**Comment by mharizanov** [comment]
This is good news, thanks for sharing the details!
I'm pretty sure it will work, but do share once you flash the new firmware..

**Comment by mharizanov** [comment]
> > In osapi.h (the SDK folder/include) changed:
> void ets_delay_us(uint16_t us);
> into:
> void ets_delay_us(long us);

That probably isn't a good idea, rather change the delay value to fit uint16t i.e. 65535

**Comment by kylix34** [comment]
The delay I think it was used when reding the ds18b20 sensor. The default value is 1000000 microseconds. Will 65535 microseconds be enough?

**Comment by mharizanov** [comment]
Conversion time for 12bit is 750ms, so rather something like this:	

**_for( i = 0; i < 75; i++ )
	    os_delay_us( 1000 ); // 750ms for 12 bit_**

**Comment by kylix34** [comment]
Great! I'll do the changes this evening and I'll let you know about the firmware. Thanks!!!!!!

**Comment by kylix34** [comment]
Changed:

1. In ds18b20.c:

	//os_delay_us( 1000000 );

	for( i = 0; i < 75; i++ )
	os_delay_us( 1000 ); // 750ms for 12 bit

2. In user_main.c:
added in the function  void ICACHE_FLASH_ATTR user_init(void) {
        int i;
	//os_delay_us(100000);
	for( i = 0; i < 1000; i++ )
	os_delay_us( 1000 );

**Comment by mharizanov** [comment]
#2 will result in 1000000 , probably watchdog will kick in before it ends

**Comment by kylix34** [comment]
Hi Martin,

do you recommend a different value for 2? The original code has a delay of 1000000

**Comment by kylix34** [comment]
The firmware compiles but it's not working while written on the NodeMCU I have. I noticed that the size of the 0x40000 was 167KB with the old SDK. With the 2.1.0 version, the size is 223KB.

Now the NodeMCU board remains with the blue LED on and in the serial it's not possible to read anything (I only see one line that gets overwritten too fast to read something).

**Comment by kylix34** [comment]
Any idea on how to debug this, Martin? Or maybe another suggestion ...

**Comment by mharizanov** [comment]
Hi,
Check if the bin files you flash would fit in the memory map and not overlap with each other or overwrite the flash configuration area. This is an ancient project, done with hardcoded firmware flash addresses and thus very prone to changes of code size.
Try to debug what causes the exception above by running xtensa-lx106-elf-addr2line -f -e ****path to the .out file***  0x40210dc8, that might provide a hint.

**Comment by kylix34** [comment]
Could it be all compiled so that it creates only one .bin file to be written?

**Comment by mharizanov** [comment]
yes, that's what was used in later versions of Eprite_tm's esp httpd project that this project is based on. You can follow his steps to fix this one, but it won't be an easy task

**Comment by kylix34** [comment]
This is what I get....not of much use:
felix@felix-HP-Pavilion-dv3-Notebook-PC:/opt/Espressif/xtensa-lx106-elf/bin$ xtensa-lx106-elf-addr2line -f -e /home/felix/Scrivania/ESP8266_Relay_Board-master/1ch_relay/build/httpd.out  0x40210dc8
flash_data_check
??:?

**Comment by kylix34** [comment]
Martin, 
I've just tried to compile Sprite_tm's last version and after I flash the firmware, my NodeMCU (4MB) acts the same way: blue LED on.
It must be somehow related to the flash size...

**Comment by mharizanov** [comment]
That's strange.. did you try esptool erase_flash?

**Comment by kylix34** [comment]
Yes, I tried first to erase the entire flash. I also tried the firmware on an Olimex ESP8266-EVB board and it has the same problem. :(

**Comment by kylix34** [comment]
This is what I'm using...

[firmware.zip](https://github.com/mharizanov/ESP8266_Relay_Board/files/1428362/firmware.zip)

**Comment by kylix34** [comment]
Hi Martin!

Do you think this is our case:https://github.com/espressif/ESP8266_NONOS_SDK/issues/2 ?
I have no clue on how to apply that patch.

**Comment by mharizanov** [comment]
Doesn't look like this is the issue.. no idea what the problem is, not sure it is worth spending the time to get it going either

**Comment by kylix34** [comment]
Well, thanks for your time!!! I think I'll stop here too as I have no idea on how to solve it. It's a pitty because it's a very nice project :(

**Comment by alandpearson** [comment]
Hi Folks,

Here is a working version of the 3ch firmware based on 2.2.1 NON-OS-SDK:
https://github.com/alandpearson/ESP8266_Relay_Board

Should work compile and flash out of the box with PlatformIO.
After PlatformIO performs the flashing, you need to write the webpages with the burn_webpages.sh script.
