### ISSUE TITLE
Add new functionality: push button to override temp

### ISSUE THREAD

**Issue by boelle** [mharizanov/ESP8266_Relay_Board#18]
as subject say i can use the code as is, but i just miss an button to press that overrides the target temp to something else

goal is to control an electrical heating panel in a flat where an autism person lives.. the staff taking care of this person has a tendency to poke their fingers at the controls allready in the panels so i thought of replacing it with something else

i have allready made a bench setup with an pi and ds18b20 but the pi zero's are to expensive given that there are at least 5 panels to control and i dont want wires in between

an esp8266 nails it as the price is much lower... it just miss's the override button to raise/boost temp for an period of time

**Comment by mharizanov** [comment]
That should be pretty trivial to achieve. I suggest starting a timer with
the desired duration with different setpoint, then reverting to the
original state.
I no longer maintain this repository and can't add features upon request,
so I leave it to the community to further enhance as needed.

**Comment by boelle** [comment]
well i'm no good coder so i will leave this one open and see if someone with the skills come by

**Comment by boelle** [comment]
@mharizanov btw... its great that sending data to emoncms is there

i read in the wiki and found the example...

input/post.json?json={relay1:%d,relay2:%d,relay3:%d,ds18b20:%s,dht22t:%s,dht22h:%s}&node=21&apikey=***APIKEY***

if i change this to:

input/post.json?json={relay1:%d,ds18b20:%s}&node=21&apikey=***APIKEY***

if not much mistaken that sends status of relay1 and the ds18b20

but are there not a way to add current target temp?
