### ISSUE TITLE
oled display

### ISSUE THREAD

**Issue by bobricius** [mharizanov/ESP8266_Relay_Board#2]
Hi, I tested firmware from zip file, working great, Is this bin firmware contain oled support? where is connected sda, scl? display address? Thermostat working only with relay1? this absolute best project on esp8266.
Maybe you can display on oled, ip address, desired temperature, wifi status, signal strengh ... selectable from web ui, this oled display have great resolution and with small font it can display much more. Great job!

**Comment by mharizanov** [comment]
Hi,
you can compile it with OLED support by uncommenting the oled.h include in user_main.c

//#include "oled.h"

I2C pins are GPIO0 - SCK and GPIO14 - SDA
Address of the OLED is 0x78

Closng this as it is not really an "issue"
