### ISSUE TITLE
GMT Offset setting does not take effect immediately

### ISSUE THREAD

**Issue by neptuneEng** [mharizanov/ESP8266_Relay_Board#4]
In the NTP dialog, the GMT Offset setting does not take effect immediately.
It requires a reboot/restart  to take effect

the following patch fixes the problem
```
> diff -u cgi.c_orig cgi.c
--- cgi.c_orig	2015-03-15 11:55:51.000000000 -0400
+++ cgi.c	2015-03-21 17:33:44.016871800 -0400
@@ -591,6 +591,7 @@
 	len=httpdFindArg(connData->postBuff, "ntp-tz", buff, sizeof(buff));
 	if (len>0) {
 		sysCfg.ntp_tz=atoi(buff);		
+		sntp_tz=sysCfg.ntp_tz;
 	}	
 	
 	CFG_Save();

```

**Comment by mharizanov** [comment]
That was a bit irritating indeed, applied the patch and pushed the fix.
Overall there are several more of this type that need fixing
