### ISSUE TITLE
muliple ds18b20

### ISSUE THREAD

**Issue by bobricius** [mharizanov/ESP8266_Relay_Board#6]
your board can read multiple ds18b20, is possible store values of more sensors to thingspeak
etc indoor, outdoor or  radiator temperature ?

**Comment by mharizanov** [comment]
That sould be fairly easy to do by hardcoding the HTTP GET to include the first three temperature sensors. I've been meaning to do it, but hadn't had the time;
pull requests are welcome

**Comment by mharizanov** [comment]
Pushed an update for this issue. Closing as resolved
