### ISSUE TITLE
Thingspeak http broadcast resets relay

### ISSUE THREAD

**Issue by spants** [mharizanov/ESP8266_Relay_Board#9]
If I enable the http broadcast, the relay/leds will reset when a call to thingspeak is being made. 
I have LEDS on the esp8266 outputs at the moment to easily spot this.
Obviously if I set latching to on it will reset to the original state.
If I turn http broadcast off (and restart), the relay state does not change ie - it doesn't reset.

**Comment by mharizanov** [comment]
I noticed that myself too and have completely replaced the broadcast code, have it running for three days now with no issues. Will push sometime soon

**Comment by spants** [comment]
Great, thanks!
